### ISSUE TITLE
Different result depending on sort value

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-api#102]
Hello team, please could you review /agents, I've just found a different output for the same query using different sorting order.

```sh
curl -k -u bar:foo "https://localhost:55000/agents?pretty&sort=id" -s | grep ip
            "ip": "127.0.0.1",
            "ip": "any",
```

```sh
curl -k -u bar:foo "https://localhost:55000/agents?pretty&sort=-id" -s | grep ip
            "ip": "any",
```

Regards,
Jesús

**Comment by mgmacias95** [comment]
Hello @jesusgn90,

Thank you so much for your report. Inspecting the code I found out the reason.

```python
if len(agent_items) > 0 and agent_items[0]['id'] == '000' and 'ip' in user_select_fields:
    agent_items[0]['ip'] = '127.0.0.1'
```

Since the manager has not its IP stored in the data, [we manually add it before returning the final result](https://github.com/wazuh/wazuh/blob/3.3/framework/wazuh/agent.py#L799).

Two solutions come to my mind:
* Store the IP in the database.
* Search for the ID 000 instead of using the first item of the list.

My favourite is the 1st one 😄 .

Best regards,
Marta

**Comment by Lifka** [comment]
Hi team,

the IP address will be stored in the database as proposed by @mgmacias95.

Regards!

**Comment by jesusgn90** [comment]
Great @Lifka thanks

**Comment by mgmacias95** [comment]
Hello @jesusgn90 and @Lifka,

This bug has been fixed in https://github.com/wazuh/wazuh/pull/970.

Thanks for reporting,
Marta
