### ISSUE TITLE
Deletion Behavior

### ISSUE THREAD

**Issue by bdwyertech** [wazuh/wazuh-api#11]
The current deletion behavior does not actually delete an agent from the `client.keys` file, it simply drops an exclamation point in front of the agent name.

https://github.com/wazuh/wazuh-api/blob/8bc8f3e57c58a1d1d8e90638abf082f1de010950/framework/wazuh/agent.py#L264

It seems that these "deleted" entries still count against the 8000 node limit -- maybe this should be deleting the matching line instead?

My workaround is `sed -i '/ !/d' /var/ossec/etc/client.keys` to get rid of those lines

**Comment by snaow** [comment]
Hi @bdwyertech,

I think deleted entries (with symbol !) don't count against the 8000 node limit. I just test it and you could have as much as obfuscated entries as you need and they won't count to the limit.

The reason behind not removing and purging the entry is because we don't want to reuse any Agent ID, meaning, if we remove an entry, for example, entry 015, next Agent added will have ID 015, and for visualization and coherence we prefer not to re use them.

Best,
Pedro.

**Comment by bdwyertech** [comment]
I'll give it another shot at some point next week -- I wrote an API client and had it looping through creates a few thousand times.  I'll have to try having it stop at 8k, delete 2k of them and keep going.

Thanks for the quick response!
