### ISSUE TITLE
Unauthenticated health status endpoint

### ISSUE THREAD

**Issue by davinerd** [wazuh/wazuh-api#119]
In some cases, an health status endpoint is needed without autentication (my use case in an AWS Application Load Balancer).

It would be nice to move the `GET /` (or a new endpoint like `GET /status`) outside of the authentication so scripts/services can check for the status of the API without using any credentials.

**Comment by jesuslinares** [comment]
Hi @davinerd,

It is interesting. We could add an endpoint just for Load balancer checks as you said. We are concerned about security (_footprinting_ - https://www.owasp.org/index.php/OAT-018_Footprinting). 

Let us investigate it.

**Comment by crd1985** [comment]
Hi @davinerd ,

maybe I am not getting the point here, but as far as I know you can configure your Load Balancer healthcheck to accept a 401 http status response as a valid health status, as shown [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html). 

Basically if you try to send any request without authorization you should receive a 401 response, indicating API is up and listening to. Otherwise you should get a connection refused error.

I hope it helps.

**Comment by evilpete** [comment]
if you are using a AWS Network load balancer the Heath check is just a TCP connect.
this will generate alerts for the TCP connections with out data

**Comment by nuttybrewer** [comment]
This is not acceptable... A TCP connection DOES NOT CONFIRM THAT THE API IS AVAILABLE, it just says that daemon is listening on a socket.

A /status that reports on a healthy state would be better. This is not only load-balancer, but k8s and other such tools as well.

**Comment by duizabojul** [comment]
What about GCP loadbalancer requiring a HTTP 200?

**Comment by n3tl0kr** [comment]
I'm behind an ALB and Keycloak so my options are limited.  Decided to do /app/wz-home# and tag on a 401.  I know the web service is responsive and i pass the alb checks.
