### ISSUE TITLE
Wazuh-API will not start (manager 3.5.0 found, 2.1.x expected)

### ISSUE THREAD

**Issue by iquaba** [wazuh/wazuh-api#145]
Following the instructions here: https://documentation.wazuh.com/2.0/installation-guide/installing-wazuh-server/wazuh_server_deb.html#wazuh-server-deb

Error that results after trying to start the wazuh-api service:
Aug 10 16:03:58 ip-10-1-0-198 nodejs[24295]: ERROR: Wazuh manager v3.5.0 found. Wazuh mana
ger v2.1.x expected. Exiting.

I fixed it by downloading the latest release and running './install_api.sh download' but just wanted to check if there was an issue with the repos or just my own fault somewhere.

**Comment by BraulioV** [comment]
Hi @iquaba ,

I think there's a problem with the repos in your machine, because the wazuh-api package downloaded belongs to the 2.1.x version of Wazuh. Also, you are following the documentation of Wazuh 2.x, so maybe you install the old repository and this overwrote the new one.

Can you please run the following commands to fix it?

1. Remove the repository file:
```shellsession
# rm /etc/apt/sources.list.d/wazuh.list
```

2. Update the repositories with `apt-get`:
```
# apt-get update
```

3. Add the latest repository:
```shellsession
# echo "deb https://packages.wazuh.com/3.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
```

4. Install the wazuh-api package:
```shellsession
# apt-get install wazuh-api
```

You can find more details here: https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_deb.html

Hope it helps.

Regards,
Braulio.

**Comment by iquaba** [comment]
Thanks, that did the trick. Didn't notice I had picked up the old docs.

**Comment by BraulioV** [comment]
Nice!! Glad to help 😄
