### ISSUE TITLE
Wazuh running on IPV6 instead of IPv4

### ISSUE THREAD

**Issue by bardie** [wazuh/wazuh-api#22]
![image](https://user-images.githubusercontent.com/10991719/30118740-79267bc8-932c-11e7-9420-b7a187608901.png)

What setting should i use to make the WAZUH api run on IPv4 and not IPv6 as illustrated on the screenshot above.

**Comment by zapililirad** [comment]
I think it's normal.
Just write in connection string in kibana IPv4 address.

**Comment by chemamartinez** [comment]
Hi @bardie,

Wazuh API is not necessarily using IPv6 for establishing the communication due to IPv6 sockets are dual stack, which means that they are prepared for working with IPv4 and IPv6 addresses on the same port.

Some services, like node in this case, open an IPv6 socket in order to make them compatible with both IP protocols.
