### ISSUE TITLE
fail to install API in centos

### ISSUE THREAD

**Issue by OrlandoCao** [wazuh/wazuh-api#240]
I have already installed python2.7, nodejs4.6, wazuh-manager3.7 in my centos6.9.
But I failed to installed wazuh0api.
error: fauked dependncies:
    nodejs >=4.6 is needed by wazuh-api-3.7.0-1.x86_64

**Comment by BraulioV** [comment]
Hi @OrlandoCao,

this error appears when NodeJS is not installed in the host using the RPM package manager. If you've installed it from sources, it won't appear in the RPM database, so the installation of the `wazuh-api` package will fail because rpm doesn't know that NodeJS is installed.

You can check if the rpm package for NodeJS is installed using the following line:
```shellsession
# rpm -qa | grep nodejs
```

If this is your case, you can install the latest NodeJS using:
```shellsession
# curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
# yum install nodejs -y
```
After that, you can try again to install the `wazuh-api` package.

Hope it helps.

Regards,
Braulio.

**Comment by mgmacias95** [comment]
Hello @OrlandoCao and @BraulioV,

It's been more than a month since the last comment was posted in this issue so I'll close it. Don't hesitate to open a new one if you need further assistance.

Best regards,
Marta
