### ISSUE TITLE
Why the Experimental API  is "experimental" ?

### ISSUE THREAD

**Issue by mrtc0** [wazuh/wazuh-api#329]
Why the [Experimental API](https://documentation.wazuh.com/current/user-manual/api/reference.html#experimental) is "experimental" ?

I want to use this API, but I am worried because I do not know why it is "experimental".

**Comment by mgmacias95** [comment]
Hello @mrtc0,

The experimental API calls are still under development: they're slower than a normal API call and they can be changed in future releases if we find a better way to implement them. That's why they're experimental. Feel free to use them but expect a higher latency than usual.

Best regards,
Marta

**Comment by mrtc0** [comment]
Thanks !
