### ISSUE TITLE
Could not connect to "wdb" socket error

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-api#334]
Hi team,

Navigating the Splunk app, the app does not show the proper information of the Agents.

For example, the agent shows `Never connected` status in one tab but in another tab shows `Active`. Could not retrieve the information of Syscheck, etc..

The web browser shows the following error of the API:

`Error:2005, "message":Could not connect to wdb socket`

I have realized that the node where the API was installed had almost 100% of disk space. And when I free up space it did not show the error anymore. Is this related to the disk space? Should not have then a more descriptive error instead of `could not connect to wdb socket`?

**Comment by mgmacias95** [comment]
Hello @MiguelCasaresRobles,

In order to stablish a connection with Wazuh DB, a file must be created (it is a UNIX socket). Having no free space in your disk makes me think Wazuh DB wasn't able to create the UNIX socket and, therefore, the API wasn't able to connect to it. Can you check if file `/var/ossec/queue/db/wdb` was created?

Best regards,
Marta

**Comment by MiguelCasaresRobles** [comment]
Hi @mgmacias95 , 

The file was already created. The API showed an error like this: `No space left on the device`.

After free up space everything is working as expected.

Regards,

Miguel Casares

**Comment by mgmacias95** [comment]
Hello @MiguelCasaresRobles,

If the API showed a descriptive error showing why the `wdb` socket wasn't working, there isn't much more that can be done to fix or prevent this issue. I'm closing the issue, but feel free to reopen it if you think this needs further discussion.

Best regards,
Marta
