### ISSUE TITLE
API alert information

### ISSUE THREAD

**Issue by mk3sta** [wazuh/wazuh-api#493]
Hi team: I'd need to extract the same information I see in the security events dashboard. My idea is to extract the information to automate the creation of reports by API.
Support spent some time taking a look at the API documentation and also reviewing the Kibana APP code to see how the security alerts dashboard is accessing the information. The Kibana APP is accessing the data though ELK, and unfortunately the API doesn't have the capability to query the alerts. 

I wish you could add that functionality, perhaps filtering by agent and a time window. Thanks! 
Regards

**Comment by vicferpoy** [comment]
Hello @mk3sta,

Unfortunately, the Wazuh API does not have any endpoint to do this since alerts are directly indexed into ElasticSearch. Anyway, we will take this in mind and study if we could add it to the roadmap.

As a workaround, you could use the **ElasticSearch API**.

To get these alerts using the ElasticSearch API, you must use the `_search` endpoint like this (keeping in mind that I have ES in the port 9200):

```
curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts*/_search"
```

That would get you every alert. If you want alerts from a certain day:

```
curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts-3.x-2020.06.03/_search"
```

You can also add queries to filter results:

```
curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts*/_search?pretty" -H 'Content-Type: application/json' -d'
{
    "query" : {
        "term" : { "rule.groups" : "syscheck" }
    }
}
'
```

You can check more about these API calls here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html

I hope this helps. Thank you again for your suggestion.

Regards,
Víctor.

**Comment by mk3sta** [comment]
Thank you very much. I will explore your suggestion. This was very helpful. Regards!

> Hello @mk3sta,
> 
> Unfortunately, the Wazuh API does not have any endpoint to do this since alerts are directly indexed into ElasticSearch. Anyway, we will take this in mind and study if we could add it to the roadmap.
> 
> As a workaround, you could use the **ElasticSearch API**.
> 
> To get these alerts using the ElasticSearch API, you must use the `_search` endpoint like this (keeping in mind that I have ES in the port 9200):
> 
> ```
> curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts*/_search"
> ```
> 
> That would get you every alert. If you want alerts from a certain day:
> 
> ```
> curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts-3.x-2020.06.03/_search"
> ```
> 
> You can also add queries to filter results:
> 
> ```
> curl -X GET "<ELASTIC_IP>:9200/wazuh-alerts*/_search?pretty" -H 'Content-Type: application/json' -d'
> {
>     "query" : {
>         "term" : { "rule.groups" : "syscheck" }
>     }
> }
> '
> ```
> 
> You can check more about these API calls here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html
> 
> I hope this helps. Thank you again for your suggestion.
> 
> Regards,
> Víctor.

Thank you very much Víctor. I will explore your suggestion. This was very helpful. Regards!
