### ISSUE TITLE
configure_api.sh does not change Kibana plugin .yml file

### ISSUE THREAD

**Issue by vicosurge** [wazuh/wazuh-api#497]
Hello there,

I noticed this a while back but thought that I may have not had enough permissions at the time, recently I replicated this and got the same error which caught my attention.

When using the configure_api.sh script inside /var/ossec/api/scripts I noticed that this does not change the file /usr/share/kibana/optimize/wazuh/config/wazuh.yml which contains the username, password, URL, and port being used by Kibana which breaks once the script runs.

How I ended up identifying this was when I tried to open the Wazuh module in Elastic 7.8.1 and 7.9.0 with an error indicating that the API was unreachable and to modify the file provided in the description (the wazuh.yml file)

For reference, this happened in Debian Sid (Experimental), Elastic environment in version 7.8.1/7.9.0.

As a side note, I was looking at the documentation but could not find anything about this issue or a reference in the section Securing the Wazuh API.

**Comment by AdriiiPRodri** [comment]
Hi @vicosurge,

Sorry for the delay, this is correct. The configure_api script will only modify the configuration of the API because it can work outside the frontend. On the other hand, we wanted to avoid that a service could modify the settings of another as this can lead to inconsistencies.

We are sorry for the inconvenience, as you say we can improve this part of the documentation to be clearer about this.

Regards

**Comment by vicosurge** [comment]
@AdriiiPRodri thank you!

That makes sense, definitely would be great to make this part of the documentation as to understand what to expect from the script and the changes it performs.
