### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by zuoshouzz** [wazuh/wazuh-api#50]
[root@localhost wazuh-api-3.0.0]# npm list
wazuh_api@3.0.0 /home/apps/wazuh3.0/wazuh-api-3.0.0
├── UNMET DEPENDENCY apicache@^0.2.0
├── UNMET DEPENDENCY body-parser@^1.15.2
├── UNMET DEPENDENCY cors@^2.7.1
├── UNMET DEPENDENCY express@^4.14.0
├── UNMET DEPENDENCY htpasswd@^2.3.4
├── UNMET DEPENDENCY http-auth@^3.0.1
└── UNMET DEPENDENCY moment@^2.15.0

npm ERR! missing: apicache@^0.2.0, required by wazuh_api@3.0.0
npm ERR! missing: body-parser@^1.15.2, required by wazuh_api@3.0.0
npm ERR! missing: cors@^2.7.1, required by wazuh_api@3.0.0
npm ERR! missing: express@^4.14.0, required by wazuh_api@3.0.0
npm ERR! missing: htpasswd@^2.3.4, required by wazuh_api@3.0.0
npm ERR! missing: http-auth@^3.0.1, required by wazuh_api@3.0.0
npm ERR! missing: moment@^2.15.0, required by wazuh_api@3.0.0

**Comment by Lifka** [comment]
Hi @zuoshouzz,

it's possible you're using `npm list` in sources directory. If you [install Wazuh API](documentation.wazuh.com/current/installation-guide/installing-wazuh-server/sources_installation.html#installing-wazuh-api) and use `npm list` in the installation directory, it should work propertly because all dependences are installed with Wazuh API.

I would appreciate your feedback to know if your problem has been solved.

Best regards,
Javier.

**Comment by Lifka** [comment]
Hi @zuoshouzz,

I also wanted to tell you that we usually recommend the installation of the available packages. I'll leave here the link for downloading them:

[Packages List](https://documentation.wazuh.com/current/installation-guide/packages-list/index.html)

Have a good day,
Javier.

**Comment by zuoshouzz** [comment]
@Lifka I installed it from a networked machine and copied the node_modules directory and ran node app.js
