### ISSUE TITLE
Change any for the real IP

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-api#74]
Hi guys, just noticed about a detail on the `/agents/{id}` request. I know this could be on the wazuh/wazuh, any case my question is if we can fetch the real IP whenever an agent has been configured using `any` as IP using the `/agents/{id}` route.

Example:
```js
{
   "error": 0,
   "data": {
      ...
      "ip": "any",
      ...
   }
}
```

If you configure it using `any` and/or using `authd` you'll see that output. 

Best,
Jesús

**Comment by jesusgn90** [comment]
Update:

Recently noticed about a complementary information regarding this issue, on the agents list from a specific group, the sorting by IP is broken if "any" appears.

```
Wazuh-Python Internal Error: u'ip'
```

Regards,
Jesús

**Comment by mgmacias95** [comment]
Hello @jesusgn90,

Regarding the bug in `GET/agents/groups/:group_id?sort=ip`, it has been fixed in https://github.com/wazuh/wazuh/commit/ff17bd157c09ec82e2b2c0eeba557c70cdb38e40.

The API shows the IP stored in `/var/ossec/var/db/global.db` database. The responsible for writing the agent's information there is `modulesd`. This issue should be reported to the Wazuh repository.

Best regards,
Marta
